var template = '# Keep this section first\n\
[scenario]\n\
name=_("Custom")\n\
description=_("Custom")\n\
\n\
[game]\n\
version=20006\n\
server_state=0\n\
metastring="JavaScript generated scenario"\n\
metaserver="meta.freeciv.org"\n\
gold=50\n\
tech=3\n\
skill_level=5\n\
timeout=0\n\
end_year=2000\n\
year=-4000\n\
techlevel=10\n\
min_players=1\n\
max_players=12\n\
nplayers=0\n\
globalwarming=0\n\
warminglevel=8\n\
nuclearwinter=0\n\
coolinglevel=8\n\
unhappysize=5\n\
cityfactor=15\n\
civilwarsize=6\n\
savepalace=0\n\
diplcost=100\n\
freecost=0\n\
conquercost=0\n\
foodbox=10\n\
techpenalty=100\n\
razechance=20\n\
civstyle=2\n\
save_nturns=0\n\
save_name="civgame"\n\
aifill=2\n\
scorelog=0\n\
fogofwar=1\n\
spacerace=0\n\
auto_ai_toggle=0\n\
diplchance=80\n\
aqueductloss=0\n\
killcitizen=1\n\
turnblock=0\n\
fixedlength=0\n\
barbarians=2\n\
onsetbarbs=60\n\
occupychance=0\n\
rulesetdir="default"\n\
demography="NASRLPEMOqrb"\n\
settlers=2\n\
explorer=1\n\
dispersion=0\n\
randseed=0\n\
\n\
[savefile]\n\
options="1.7 startoptions spacerace2 rulesets diplchance_percent startpos riversoverlay"\n\
\n\
[map]\n\
topology_id=3\n\
width={width}\n\
height={height}\n\
seed=0\n\
have_specials=0\n\
riches=10\n\
generator=0\n\
is_earth=0\n\
have_huts=0\n\
huts=0\n\
landpercent=25\n\
swampsize=0\n\
deserts=0\n\
riverlength=0\n\
mountains=0\n\
forestsize=0\n\n';
